title: Presentations with Reveal.js
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ubc-library-rc/intro-revealjs/\">View workshop content in GitHub</a>"
